version: '3.4'

services:
  kafka1:
    image: kafka:2.12-2.6.2
    restart: always
    container_name: kafka1
    ports:
      - 9092:9092
    volumes:
      - /data/kakfa/kafka1/data:/data/kafka-logs
      - /data/kakfa/kafka1/config:/opt/kafka/config
      - /data/kakfa/kafka1/logs:/opt/kafka/logs
    networks:
      - zk-network

  kafka2:
    image: kafka:2.12-2.6.2
    restart: always
    container_name: kafka2
    ports:
      - 9093:9093
    volumes:
      - /data/kakfa/kafka2/data:/data/kafka-logs
      - /data/kakfa/kafka2/config:/opt/kafka/config
      - /data/kakfa/kafka2/logs:/opt/kafka/logs
    networks:
      - zk-network

  kafka3:
    image: kafka:2.12-2.6.2
    restart: always
    container_name: kafka3
    ports:
      - 9094:9094
    volumes:
      - /data/kakfa/kafka3/data:/data/kafka-logs
      - /data/kakfa/kafka3/config:/opt/kafka/config
      - /data/kakfa/kafka3/logs:/opt/kafka/logs
    networks:
      - zk-network

networks:
  zk-network:
    external: true
